# version: "3.8"
services:
  db:
    container_name: mbptl-db
    build:
      context: database
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_USER: library
      MYSQL_PASSWORD: p@ssw0rd123
      MYSQL_ROOT_PASSWORD: rootp@ssw0rd123
    volumes:
      - ./database/dump:/docker-entrypoint-initdb.d
      - ./database/conf:/etc/mysql/conf.d
      - persistent:/var/lib/mysql
    networks:
      - default
    restart: always

  bookstore:
    container_name: mbptl-bookstore
    build:
      context: bookstore
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./bookstore/www/:/var/www/html/
    links:
      - db
    depends_on:
      - db
    networks:
      - default
    restart: always

  administrator:
    container_name: mbptl-administrator
    build:
      context: administrator
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    links:
      - db
    depends_on:
      - db
    networks:
      - default
    restart: always

volumes:
  persistent:
