services:
  mbptl-library:
    build:
      context: mbptl-library
      dockerfile: Dockerfile
    container_name: mbptl-library
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${WEB1_PORT:-80}:80"
      - "${WEB2_PORT:-8080}:8080"
      - "127.0.0.1:${DB_PORT:-3306}:3306"
    command: /start.sh
    restart: unless-stopped

  mbptl-internal:
    build:
      context: mbptl-internal
      dockerfile: Dockerfile
    container_name: mbptl-internal
    ports:
      - "127.0.0.1:${WEB_INTERNAL_PORT:-1337}:1337"
    links:
      - mbptl-library
    depends_on:
      - mbptl-library
    restart: unless-stopped

volumes:
  db_data: